name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: Swatinem/rust-cache@v2
    - run: make fmt

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: Swatinem/rust-cache@v2
    - run: cargo install cargo-shear --locked
    - run: make clippy
    - run: make shear

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: Swatinem/rust-cache@v2
    - run: cargo check --all --tests
    - run: cd criner-waste-report && cargo check --tests && cargo check --tests --no-default-features
    - run: cargo test --all

  package-size:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: Swatinem/rust-cache@v2
    - name: Check crate package size
      run: |
        curl -LSfs https://raw.githubusercontent.com/the-lean-crate/cargo-diet/master/ci/install.sh | \
         sh -s -- --git the-lean-crate/cargo-diet --tag v1.4.0 --target x86_64-unknown-linux-musl

        cargo diet -n --package-size-limit 15KB
        (cd criner && cargo diet -n --package-size-limit 50KB)
        (cd criner-waste-report && cargo diet -n --package-size-limit 18KB)
